#!/bin/sh

uci set wireless.default_radio0.ssid='Cudy TR3000'
uci set wireless.default_radio0.key='12345678'
uci set wireless.default_radio0.encryption='psk2'

uci set wireless.default_radio1.ssid='Cudy TR3000-5G'
uci set wireless.default_radio1.key='12345678'
uci set wireless.default_radio1.encryption='psk2'

uci set wireless.default_radio0.disabled='0'
uci set wireless.default_radio1.disabled='0'

uci commit wireless

exit 0
